import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'
import { Nerko_One } from '@next/font/google'

const inter = Nerko_One({
  weight: '400',
  subsets: ['latin']})


export default function Home() {
  return (
    <>
      <Head>

        <title>Jenny's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/jennyicon.svg"/>
        
      </Head>
      <main className={styles.main}>

      <div className={styles.nav}>
<a className={styles.yuh} href="/">home </a>
<Link className={styles.yuh} href="/about">about </Link>
<Link className={styles.yuh} href="/work">work </Link>
<h4 className={styles.name}>JB</h4>
</div>

<div className={styles.me2}>
<img src='/jennyicon.svg' width={400}></img>

<div>
<h1 className={styles.aboutme}>about me</h1>
<div className={styles.caption}>
    hello! my name is jenny and i am studying digital design and development. <br></br> 
    i can code html, css, and javascipt, however i focus more on graphic and web <br></br>
    design. i have been coding and designing for less than a year, but i am excited <br></br>
     to grow and learn more!
</div>
</div>
</div>

<hr className={styles.line}></hr>

<h1 className={styles.contact}>contact me!</h1>
<div className={styles.email}>
    email: jbui22@my.bcit.ca
</div>
<div className={styles.contactme}>do you have any questions? please don't hesitate to contact me by email! </div>










      </main>
    </>
  )
}