import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'
import { Nerko_One } from '@next/font/google'

const inter = Nerko_One({
  weight: '400',
  subsets: ['latin']})


export default function Home() {
  return (
    <>
      <Head>

        <title>Jenny's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/jennyicon.svg"/>
        
      </Head>
      <main className={styles.main}>

      <div className={styles.nav}>
<a className={styles.yuh} href="/">home </a>
<Link className={styles.yuh} href="/about">about </Link>
<Link className={styles.yuh} href="/work">work </Link>
<h4 className={styles.name}>JB</h4>
</div>

<div className={styles.me}>
<img src='/jennyicon.svg' width={500}></img>
</div>

<div className={styles.myname}>
  <h1>jenny</h1> 
  <h1 className={styles.bui}>bui</h1>
</div>

<h1 className={styles.title}> web developer and designer</h1>






      </main>
    </>
  )
}
