import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'
import { Nerko_One } from '@next/font/google'


const inter = Nerko_One({
  weight: '400',
  subsets: ['latin']})


export default function Home() {
  return (
    <>
      <Head>

        <title>Jenny's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/jennyicon.svg"/>
        
      </Head>
      <main className={styles.main}>

      <div className={styles.nav}>
<a className={styles.yuh} href="/">home </a>
<Link className={styles.yuh} href="/about">about </Link>
<Link className={styles.yuh} href="/work">work </Link>
<h4 className={styles.name}>JB</h4>
</div>

<h1 className={styles.projects}>Piano Palace Academy Poster</h1>

<div className={styles.group}>
<div className={styles.piano}>
<img src='\Asset 12.png' width={350}></img>  &nbsp; &nbsp; 
</div>

<div className={styles.piano2}>
<img src='\Asset 14.png' width={350}></img> &nbsp; &nbsp; 
<img src='\Asset 13.png' width={350}></img> &nbsp; &nbsp;
</div>

</div>




      </main>
    </>
  )
}