import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'
import { Nerko_One } from '@next/font/google'


const inter = Nerko_One({
  weight: '400',
  subsets: ['latin']})


export default function Home() {
  return (
    <>
      <Head>

        <title>Jenny's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/jennyicon.svg"/>
        
      </Head>
      <main className={styles.main}>

      <div className={styles.nav}>
<a className={styles.yuh} href="/">home </a>
<Link className={styles.yuh} href="/about">about </Link>
<Link className={styles.yuh} href="/work">work </Link>
<h4 className={styles.name}>JB</h4>
</div>

<h1 className={styles.projects}>my projects</h1>



<h2 className={styles.illtitle}>illustrations</h2>

<div className={styles.illustration}>
<a href="/tuliptown"><img className={styles.tulips} src='\Artboard 1.png' width={350}></img> </a> &nbsp; &nbsp; &nbsp;
<a href="/toaster"><img className={styles.tulipss} src='\toaster.png' width={350}></img> </a>  &nbsp; &nbsp; &nbsp;
<a href="/piano"><img className={styles.tulips} src='\Asset 12.png' width={368}></img> </a>  &nbsp; &nbsp; &nbsp;
</div>

      </main>
    </>
  )
}